{
"status": 200,
"purchases": [
{
"subscription_expiration_date": 4102412400000,
"product_identifier": "com.canary.purchase.subscription.bundle",
"transaction_id": "470000000000000",
"original_purchase_date": 1577804400000,
"platform": "ios"
}
],
"devices": [
{
"location": "United States",
"first_seen": 1577804400000.292,
"active": true,
"id": "XXXXXXXXXXYYYYYYYYYYZZZZZZZZZZOO",
"platform": "ios",
"type": "ios",
"name": "Canary",
"last_seen": 4102412400000.502
}
]
}
