var _0x329492 = {
    request_date_ms: 1591358081473,
    request_date: "2020-06-05T11:54:41Z",
    subscriber: {
        entitlements: {
            all: {
                expires_date: "2030-01-01T01:01:01Z",
                grace_period_expires_date: null,
                product_identifier: "com.ziheng.aphrodite.lifetime",
                purchase_date: "2020-01-01T01:01:01Z"
            },
            "com.ziheng.aphrodite.lifetime": {
                billing_issues_detected_at: null,
                expires_date: "2030-01-01T01:01:01Z",
                grace_period_expires_date: null,
                is_sandbox: !1,
                original_purchase_date: "2020-01-01T01:01:01Z",
                period_type: "normal",
                purchase_date: "2020-01-01T01:01:01Z",
                store: "app_store",
                unsubscribe_detected_at: null,
                product_identifier: "com.ziheng.aphrodite.lifetime"
            }
        },
        first_seen: "2000-01-01T01:01:01Z",
        last_seen: "2030-01-01T01:01:01Z",
        management_url: "itms-apps://apps.apple.com/account/subscriptions",
        non_subscriptions: {
            "com.ziheng.aphrodite.lifetime": [{
                id: "123",
                is_sandbox: !1,
                original_purchase_date: "2019-12-01T00:00:00Z",
                purchase_date: "2019-12-01T00:00:00Z",
                product_identifier: "com.ziheng.aphrodite.lifetime",
                store: "app_store"
            }],
            all: [{
                id: "123",
                is_sandbox: !1,
                original_purchase_date: "2019-12-01T00:00:00Z",
                purchase_date: "2019-12-01T00:00:00Z",
                product_identifier: "com.ziheng.aphrodite.lifetime",
                store: "app_store"
            }]
        },
        original_app_user_id: "0099LK05-2799-489J-09CD-D9IJSEB09876",
        original_application_version: "20",
        original_purchase_date: "2000-01-01T01:01:01Z",
        other_purchases: {
            "com.ziheng.aphrodite.lifetime": {
                billing_issues_detected_at: null,
                expires_date: "2030-01-01T01:01:01Z",
                grace_period_expires_date: null,
                is_sandbox: !1,
                original_purchase_date: "2020-01-01T01:01:01Z",
                period_type: "normal",
                purchase_date: "2020-01-01T01:01:01Z",
                store: "app_store",
                unsubscribe_detected_at: null
            }
        },
        subscriptions: {
            "com.ziheng.aphrodite.lifetime": {
                billing_issues_detected_at: null,
                expires_date: "2030-01-01T01:01:01Z",
                grace_period_expires_date: null,
                is_sandbox: !1,
                original_purchase_date: "2020-01-01T01:01:01Z",
                period_type: "normal",
                purchase_date: "2020-01-01T01:01:01Z",
                store: "app_store",
                unsubscribe_detected_at: null
            }
        }
    }
};

 $done({
        body: JSON.stringify(_0x329492)
    })
