var App = {
  "_id": {
    "$oid": "6217981da0d90374a64bf026"
  },
  "watchList": [{
    "app": [],
    "title": null,
    "info": null,
    "up": 0,
    "down": 0,
    "comment": 0,
    "watch": 0,
    "user": null
  }],
  "username": "Peppa",
  "premium": true,
  "mod": true,
  "private": true,
  "region": "JP",
  "wish": [],
  "own": ["https://is4-ssl.mzstatic.com/image/thumb/Purple116/v4/21/fc/46/21fc46ef-3858-0aca-8bd3-140525f4fb39/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/{w}x{h}{c}.{f}"],
  "up": [],
  "down": [],
  "follows": [],
  "follower": [],
  "image": {
    "$oid": "000000000000000000000000"
  },
  "wishCount": 0,
  "ownCount": 1,
  "upCount": 0,
  "downCount": 0,
  "followsCount": 0,
  "followerCount": 0,
  "listCount": 0,
  "list": [{
    "app": [],
    "title": null,
    "info": null,
    "up": 0,
    "down": 0,
    "comment": 0,
    "watch": 0,
    "user": null
  }],
  "watchListCount": 0,
  "commentApp": [],
  "commentAppCount": 0,
  "totalCommentAppCount": 0,
  "upArtistCount": 0,
  "downArtistCount": 0,
  "watchArtistCount": 0,
  "youfollow": 0,
  "yourfollower": 0
};
$done({
        body: JSON.stringify(App)
    })
